mystr=("sourik is a good boy")
"""print(len(mystr))
print(mystr)
print(mystr[0])
print(mystr[0:])
print(mystr[0:7])
print(mystr[::])
print(mystr[::3])
print(mystr[-4:-2])
print(mystr[::-2])
"""
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith("is"))
print(mystr.count("v"))
print(mystr.capitalize())
print(mystr.find("is"))
print(mystr.lower())
print(mystr.upper())
print(mystr.replace("is","are"))

